export type SliderConfig = {
  direction: "horizontal" | "vertical";
  slidesPerView: number;
  slidesPerGroup: number;
  rows: number;
  centered: boolean;
  spaceBetween: number;
  initialSlide: number;
  autoHeight: boolean;
  grabCursor: boolean;
  slideToClicked: boolean;
  loopMode: "disabled" | "infinite";
  effect: "slide" | "fade" | "cube" | "coverflow";
  transitionDuration: number;
  navigation: boolean;
  pagination: boolean;
  autoplay: boolean;
  scrollbar: boolean;
  freeMode: boolean;
};
